### ISSUE TITLE
Utilizzo in produzione e accreditamento AgID

### ISSUE THREAD

**Issue by erapsag** [italia/spid-keycloak-entando#1]
Salve a tutti, questa è più una domanda che una Issue.
La soluzione da voi proposta, di implementare SPID attraverso Keycloak e l'utilizzo di un [plugin](https://github.com/lscorcia/keycloak-spid-provider), è davvero molto interessante ed anche io mi sto cimentando in un implementazione simile.

Mi chiedevo se la vostra soluzione era già in produzione e se avesse passato l'accreditamento da parte di AgID.

**Comment by GermanoGiudici** [comment]
Ciao @erapsag. Il plugin standalone è stato utilizzato per produrre soluzioni che già sono in produzione, tra l'altro è stato rilasciato un aggiornamento pochi giorni fa. La soluzione integrata con entando (questo repository), non è ancora stato testato in produzione. Aspettiamo beta tester con cui confrontarci :)

**Comment by peppelinux** [comment]
@erapsag prova anche a seguire questo per opportuni confronti
https://github.com/lscorcia/keycloak-spid-provider

quando sarà in produzione lo trasferiremo su dev ita

**Comment by erapsag** [comment]
@GermanoGiudici @peppelinux grazie delle risposte immediate.
Si, seguo già il repo di l.scorcia, ho aperto anche una Issue di recente. E a proposito di questo volevo confrontarmi con altra gente che utilizza il suo plugin.
Voi lo usate anche in altri progetti in cui sia già in produzione e/o avete sostenuto la procedura di accreditamento con AgID?
Perchè ho dei dubbi riguardo ad alcuni test sulle "Response" effettuati tramite lo "spid-saml-check".
Avete avuto modo di effettuare questi test ed avete trovato corrispondenza?

**Comment by GermanoGiudici** [comment]
Guarda non l'ho provato in produzione come ti dicevo, ma ho visto il codice e l'integrazione con keycloak e mi sembra abbastanza semplice da debuggure anche in caso di problemi. A me ha fatto decisamente una buona impressione, tant'è vero che lo abbiamo usato per la nostra evoluzione. Tra l'altro mi era stato consigliato anche dai developer di sielte, che fanno idp.
